version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/iccautotravel
      # Thêm các biến môi trường khác từ .env tại đây
    volumes:
      - .:/app # Mount code để phát triển local (tùy chọn)
      - /app/node_modules # Ngăn không cho node_modules bị ghi đè bởi mount volume

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iccautotravel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: